from rest_framework.routers import DefaultRouter
from .views import *

router = DefaultRouter()
router.register(r'utilisateurs', UtilisateurViewSet)
router.register(r'types-restaurant', TypeRestaurantViewSet)
router.register(r'restaurants', RestaurantViewSet)
router.register(r'images-restaurants', ImageRestaurantViewSet)
router.register(r'administrateurs', AdministrateurViewSet)
router.register(r'clients', ClientViewSet)
router.register(r'images-clients', ImageClientViewSet)
router.register(r'domiciles', DomicileViewSet)
router.register(r'domiciles-clients', DomicileClientViewSet)
router.register(r'villes', VilleViewSet)
router.register(r'domiciles-restaurateurs', DomicileRestaurateurViewSet)
router.register(r'notifications', NotificationViewSet)
router.register(r'commandes', CommandeViewSet)
router.register(r'details-commandes', DetailCommandeViewSet)
router.register(r'categories-menus', CategorieMenuViewSet)
router.register(r'articles-menus', ArticleMenuViewSet)
router.register(r'menus', MenuViewSet)
router.register(r'images-menus', ImageMenuViewSet)
router.register(r'disponibilites-menus', DisponibiliteMenuViewSet)
router.register(r'horaires', HoraireViewSet)
router.register(r'evaluations', EvaluationViewSet)
router.register(r'tables', TableViewSet)
router.register(r'reservations-tables', ReservationTableViewSet)
router.register(r'statuts-reservations', StatutReservationViewSet)
router.register(r'coupons', CouponViewSet)
router.register(r'paiements', PaiementViewSet)
router.register(r'methodes-paiement', MethodePaiementViewSet)
router.register(r'livraisons', LivraisonViewSet)
router.register(r'statuts-commandes', StatutCommandeViewSet)
router.register(r'statuts-livraisons', StatutLivraisonViewSet)
router.register(r'details-livraisons', DetailLivraisonViewSet)
router.register(r'livreurs', LivreurViewSet)
router.register(r'types-vehicules', TypeVehiculeViewSet)
router.register(r'images-livreurs', ImageLivreurViewSet)

urlpatterns = router.urls
