# Generated by Django 5.1.4 on 2025-01-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_imageclient_image_alter_imagelivreur_image_and_more'),
        ('restaurant', '0002_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiciles', to='location.ville')),
            ],
            options={
                'verbose_name': 'Domicile',
            },
        ),
        migrations.CreateModel(
            name='DomicileClient',
            fields=[
                ('domicile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='location.domicile')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
            options={
                'verbose_name': 'Domicile de Client',
            },
            bases=('location.domicile',),
        ),
        migrations.CreateModel(
            name='DomicileStore',
            fields=[
                ('domicile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='location.domicile')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.store')),
            ],
            options={
                'verbose_name': 'Domicile Restaurateur',
            },
            bases=('location.domicile',),
        ),
    ]
