# Generated by Django 5.1.4 on 2025-01-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Catégorie de Menu',
                'verbose_name_plural': 'Catégories de Menus',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.FloatField()),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('reduction', models.FloatField()),
                ('date_valide_debut', models.DateTimeField()),
                ('date_valide_fin', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='DetailLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_real_livraison', models.DateTimeField()),
                ('frais', models.FloatField()),
            ],
            options={
                'verbose_name': 'Détail de Livraison',
                'verbose_name_plural': 'Détails de Livraisons',
            },
        ),
        migrations.CreateModel(
            name='ImageLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/livreurs/')),
            ],
            options={
                'verbose_name': 'Image de Livreur',
                'verbose_name_plural': 'Images de Livreurs',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
            },
        ),
        migrations.CreateModel(
            name='MethodePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Méthode de Paiement',
                'verbose_name_plural': 'Méthodes de Paiement',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_paiement', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Réservation de Table',
                'verbose_name_plural': 'Réservations de Tables',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('proprietaire', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('total_table', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='StatutLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Statut de Livraison',
                'verbose_name_plural': 'Statuts de Livraisons',
            },
        ),
        migrations.CreateModel(
            name='TypeRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Type de Restaurant',
                'verbose_name_plural': 'Types de Restaurants',
            },
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Type de Véhicule',
                'verbose_name_plural': 'Types de Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_passe', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_postal', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='ArticleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.categoriemenu')),
            ],
            options={
                'verbose_name': 'Article de Menu',
                'verbose_name_plural': 'Articles de Menu',
            },
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.commande')),
            ],
            options={
                'verbose_name': 'Détail de Commande',
                'verbose_name_plural': 'Détails de Commandes',
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.CharField(max_length=255)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.articlemenu')),
            ],
            options={
                'verbose_name': 'Disponibilité de Menu',
                'verbose_name_plural': 'Disponibilités de Menus',
            },
        ),
        migrations.CreateModel(
            name='DomicileClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.client')),
            ],
            options={
                'verbose_name': 'Domicile de Client',
                'verbose_name_plural': 'Domiciles de Clients',
            },
        ),
        migrations.CreateModel(
            name='ImageClient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='clients/')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gokaly.client')),
            ],
            options={
                'verbose_name': 'Image de Client',
                'verbose_name_plural': 'Images de Clients',
            },
        ),
        migrations.CreateModel(
            name='ImageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/menus/')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.articlemenu')),
            ],
            options={
                'verbose_name': 'Image de Menu',
                'verbose_name_plural': 'Images de Menus',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('articles', models.ManyToManyField(to='gokaly.articlemenu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='ImageRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/restaurants/')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.restaurant')),
            ],
            options={
                'verbose_name': 'Image de Restaurant',
                'verbose_name_plural': 'Images de Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField()),
                ('jour_ouverture', models.DateField()),
                ('heure_fermeture', models.TimeField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.restaurant')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.restaurant')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='DomicileRestaurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.restaurant')),
            ],
            options={
                'verbose_name': 'Domicile de Restaurateur',
                'verbose_name_plural': 'Domiciles de Restaurateurs',
            },
        ),
        migrations.CreateModel(
            name='StatutCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=255)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.commande')),
            ],
            options={
                'verbose_name': 'Statut de Commande',
                'verbose_name_plural': 'Statuts de Commandes',
            },
        ),
        migrations.CreateModel(
            name='StatutReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=255)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.reservationtable')),
            ],
            options={
                'verbose_name': 'Statut de Réservation',
                'verbose_name_plural': 'Statuts de Réservation',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('capacite', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.restaurant')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.AddField(
            model_name='reservationtable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.table'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gokaly.typerestaurant'),
        ),
        migrations.AddField(
            model_name='client',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.utilisateur'),
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gokaly.utilisateur')),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Domicile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domiciles', to='gokaly.ville')),
            ],
            options={
                'verbose_name': 'Domicile',
                'verbose_name_plural': 'Domiciles',
            },
        ),
    ]
