# Generated by Django 5.1.4 on 2025-01-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('last_logged', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Livreur',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.utilisateur')),
                ('nom', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
            },
            bases=('account.utilisateur',),
        ),
        migrations.CreateModel(
            name='RestoManager',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.utilisateur')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Administrateur Resto',
            },
            bases=('account.utilisateur',),
        ),
        migrations.CreateModel(
            name='StoreManager',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.utilisateur')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Responsable Point de vente',
            },
            bases=('account.utilisateur',),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.utilisateur')),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Super administrateur',
            },
            bases=('account.utilisateur',),
        ),
        migrations.CreateModel(
            name='ImageLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_livreur/')),
                ('livreur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_livreur', to='account.livreur')),
            ],
            options={
                'verbose_name': 'Image Livreur',
            },
        ),
        migrations.CreateModel(
            name='ImageClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_clients/')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_client', to='account.client')),
            ],
            options={
                'verbose_name': 'Image Client',
            },
        ),
        migrations.CreateModel(
            name='ImageRestoManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_resto_manager/')),
                ('restoManager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_resto_manager', to='account.restomanager')),
            ],
            options={
                'verbose_name': 'Image Administrateur Resto',
            },
        ),
        migrations.CreateModel(
            name='ImageStoreManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_store_manager/')),
                ('storeManager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_store_manager', to='account.storemanager')),
            ],
            options={
                'verbose_name': 'Image Gérant Point de vente',
            },
        ),
        migrations.CreateModel(
            name='ImageSuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_super_admin/')),
                ('superAdmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_resto_manager', to='account.superadmin')),
            ],
            options={
                'verbose_name': 'Image Super Administrateur',
            },
        ),
    ]
