# Generated by Django 5.1.4 on 2025-01-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclient',
            name='image',
            field=models.ImageField(upload_to='images/clients/'),
        ),
        migrations.AlterField(
            model_name='imagelivreur',
            name='image',
            field=models.ImageField(upload_to='images/livreur/'),
        ),
        migrations.AlterField(
            model_name='imagerestomanager',
            name='image',
            field=models.ImageField(upload_to='images/resto_manager/'),
        ),
        migrations.AlterField(
            model_name='imagestoremanager',
            name='image',
            field=models.ImageField(upload_to='images/store_manager/'),
        ),
        migrations.AlterField(
            model_name='imagesuperadmin',
            name='image',
            field=models.ImageField(upload_to='images/super_admin/'),
        ),
    ]
