# Generated by Django 5.1.4 on 2025-01-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_imageclient_image_alter_imagelivreur_image_and_more'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('store_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.storemanager')),
            ],
            options={
                'verbose_name': 'Point de vente',
            },
        ),
    ]
